server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: apache-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: apache
          __path__: /logs/apache/*log

  - job_name: app-events
    static_configs:
      - targets: [localhost]
        labels:
          job: app
          __path__: /logs/app/app_events.log