server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app
    static_configs:
      - labels:
          job: app
          __path__: /logs/app/app_events.log
    pipeline_stages:
      - json:
          expressions:
            ts:
            source_ip:
            username:
            event_type:
            message:
            user_agent:
            demo:
            geo_country:
            geo_region:
            geo_city:
            geo_lat:
            geo_lon:
            geo_org:
      - labels:
          source_ip:
          event_type:
          demo:
          geo_country:
          geo_city:
      - timestamp:
          source: ts
          format: RFC3339

  - job_name: apache
    static_configs:
      - labels:
          job: apache
          __path__: /logs/apache/*.log